function CUR_FEAT=feature_extraction(segment)
MN=mean(segment);
STaD=std(segment);
MAX=max(segment);
MIN=min(segment);
SKEW=skewness(segment);
KURT = kurtosis(segment);
MD=median(segment);
del=[0, 4];
thet=[4, 8];
al=[8, 13];
bet=[13, 30];
all = [0 30];
fs=200;
ALFA=bandpower(segment, fs, al);
BETA=bandpower(segment, fs, bet);
DELTA=bandpower(segment, fs, del);
THETA=bandpower(segment, fs, thet);
rel = [ALFA BETA DELTA THETA]/bandpower(segment, fs, all);
CUR_FEAT = [MN STaD MAX MIN SKEW KURT MD ALFA BETA DELTA THETA rel];  
end